version: '3.9'

services:
    app:
        container_name: auth-ms
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
            - /app/prisma

volumes:
    nodetsapi: